apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: spring-petclinic
  name: spring-petclinic
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
        - image: quay.io/demo-proj/spring-petclinic:latest
          imagePullPolicy: Always
          name: spring-petclinic
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
      securityContext: {}
status: {}
